# Generated by Django 5.2.3 on 2025-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='template',
            name='template_file',
            field=models.CharField(blank=True, default='', help_text='Django template filename, e.g. resume_templates/template1.html', max_length=100),
        ),
    ]
