# Generated by Django 5.2.3 on 2025-07-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_template_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='awards',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='interests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='publications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='references',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='volunteering',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experience',
            field=models.JSONField(default=list),
        ),
    ]
